language: python

python:
    - 2.6

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install build-essential
    - sudo apt-get install gengetopt
    - sudo apt-get install libgsl0-dev
    - git clone https://github.com/TransformingMusicology/libaudioDB.git
    - git clone https://github.com/TransformingMusicology/audioDB.git
    - git clone https://github.com/bregmanstudio/BLAST.git
    - make -C libaudioDB/
    - sudo make -C libaudioDB/ install
    - make -C audioDB/
    - sudo make -C audioDB/ install

script:
    - pip install -e .

notifications:
    email: false