language: python

python:
    - 2.6

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install build-essential
    - sudo apt-get install gengetopt

script:
    - pip install -e .

notifications:
    email: false