language: python

python:
    - 2.6

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install build-essential
    - sudo apt-get install gengetopt
    - sudo apt-get install libgsl0-dev
    - sudo apt-get install help2man
    - sudo apt-get install libsndfile1-dev
    - sudo apt-get install libfftw3-dev
    - git clone https://github.com/TransformingMusicology/libaudioDB.git
    - git clone https://github.com/TransformingMusicology/audioDB.git
    - git clone https://github.com/bregmanstudio/BLAST.git
    - make -C libaudioDB/
    - sudo make -C libaudioDB/ install
    - make HELP2MAN="help2man --no-discard-stderr" -C audioDB/
    - sudo make -C audioDB/ install
    - make -C BLAST/fftExtract/
    - sudo cp BLAST/fftExtract/fftExtract /usr/local/bin

script:
    - pip install -r requirements.txt
    - pip install -e .

notifications:
    email: false