language: python

python:
    - 2.6

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install build-essential
    - sudo apt-get install gengetopt
    - git clone https://github.com/TransformingMusicology/libaudioDB.git
    - git clone https://github.com/TransformingMusicology/audioDB.git
    - git clone https://github.com/bregmanstudio/BLAST.git
    - make -C libaudioDB/

script:
    - pip install -e .

notifications:
    email: false