language: python

python:
    - 2.7

notifications:
    email: false

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm
    - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose dateutil pandas statsmodels scikit-learn
    - conda install --yes -c dan_blanchard python-coveralls nose-cov
    - conda install --yes -c https://conda.binstar.org/weiyan libsndfile scikit-audiolab

    - sudo apt-get update -qq
    - sudo apt-get install -y build-essential gengetopt libgsl0-dev help2man libsndfile1-dev libfftw3-dev imagemagick lame

    - git clone https://github.com/TransformingMusicology/libaudioDB.git
    - git clone https://github.com/TransformingMusicology/audioDB.git
    - git clone https://github.com/bregmanstudio/BLAST.git

    - make -C libaudioDB/
    - sudo make -C libaudioDB/ install

    - make HELP2MAN="help2man --no-discard-stderr" -C audioDB/
    - sudo make -C audioDB/ install
    - ldd /usr/local/bin/audioDB
    - echo '/usr/local/lib' > libaudioDB.conf
    - sudo mv libaudioDB.conf /etc/ld.so.conf.d/
    - sudo ldconfig 
    - ldd /usr/local/bin/audioDB
    - audioDB --help

    - make -C BLAST/fftExtract/
    - sudo cp BLAST/fftExtract/fftExtract /usr/local/bin

    - wget -q http://download.linuxaudio.org/lilypond/binaries/linux-64/lilypond-2.19.21-1.linux-64.sh
    - sh lilypond-2.19.21-1.linux-64.sh --batch
    - export PATH=/home/travis/bin:$PATH
    - lilypond --help

install:
    - pip install -r requirements.txt
    - pip install -e .
    - cp sasha/sasha.example.cfg sasha/sasha.cfg

script:
    - coverage run -a sasha/scr/bootstrap-testing-environment
    - coverage run -a `which py.test` -rf -vv

after_success:
    coveralls