language: python

python:
    - 2.7

virtualenv:
    system_site_packages: true

before_install:
    - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
    - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt  
    - sudo apt-get update -qq
    - sudo apt-get install -qq build-essential
    - sudo apt-get install -qq gengetopt
    - sudo apt-get install -qq libgsl0-dev
    - sudo apt-get install -qq help2man
    - sudo apt-get install -qq libsndfile1-dev
    - sudo apt-get install -qq libfftw3-dev
    - sudo apt-get install -qq python-numpy python-scipy python-matplotlib
    - git clone https://github.com/TransformingMusicology/libaudioDB.git
    - git clone https://github.com/TransformingMusicology/audioDB.git
    - git clone https://github.com/bregmanstudio/BLAST.git
    - make -C libaudioDB/
    - sudo make -C libaudioDB/ install
    - make HELP2MAN="help2man --no-discard-stderr" -C audioDB/
    - sudo make -C audioDB/ install
    - make -C BLAST/fftExtract/
    - sudo cp BLAST/fftExtract/fftExtract /usr/local/bin

script:
    - pip install -r requirements.txt
    - pip install -e .

notifications:
    email: false