#! /usr/bin/env python

import os
import sasha
from abjad.tools import documentationtools


sasha_root = sasha.__path__[0]


class SASHAAPIGenerator(documentationtools.AbjadAPIGenerator):
    r'''API generator for the sasha package.
    '''

    _api_title = 'SASHA API'

    _package_descriptions = {
        'core': 'Core packages',
        }

    @property
    def docs_api_index_path(self):
        import sasha
        return os.path.join(
            sasha.__path__[0],
            'docs',
            'source',
            'index.rst',
            )

    @property
    def path_definitions(self):
        import sasha
        tools_code_path = os.path.join(
            sasha.__path__[0],
            'tools',
            )
        tools_docs_path = os.path.join(
            sasha.__path__[0],
            'docs',
            'source',
            'tools',
            )
        tools_package_prefix = 'sasha.tools.'
        tools_triple = (
            tools_code_path,
            tools_docs_path,
            tools_package_prefix,
            )
        all_triples = [tools_triple]
        return all_triples

    @property
    def root_package(self):
        return 'sasha'

    @property
    def tools_package_path_index(self):
        return 2


if __name__ == '__main__':
    SASHAAPIGenerator()(verbose=True)